### PR TITLE
feat: initial liquidity deduction for pair protection

### PR DESCRIPTION
**Pull request by jhlee-young**
## Summary of changes

<Describe summary of major changes here>

## Report of required housekeeping

- [ ] Github issue OR spec proposal link
- [ ] Wrote tests
- [ ] Added a relevant changelog entry to CHANGELOG.md

----

## (FOR ADMIN) Before merging

- [ ] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

### CODE REVIEW

**Review by JoowonYun — APPROVED** [review]

**Review by jbamlee — COMMENTED** [review]
LGTM. 
Could you add the message for the `initial_liquidity` subtraction?

**Review by jbamlee — APPROVED** [review]

**Comment by jhlee-young** [comment]
> LGTM. Could you add the message for the `initial_liquidity` subtraction?

wouldn't it be enough to leave a mint message to the contract itself?
https://github.com/terraswap/terraswap/pull/67/files#diff-c6675e218cf0f98b85adce170716676bb4db62773085ceacf0f313577ecfee22R301

**Comment by JoowonYun** [comment]
> LGTM. Could you add the message for the `initial_liquidity` subtraction?

@jbamlee @jhlee-young 
It seems sufficient to log the attributes when cw20's mint is processed.

**Comment by jbamlee** [comment]
IMO, it is better to have an additional message.
- the event messages are ambiguous 
```
_contract_address terra1g6c5wrcw0sfhgl7nh2pun7v4jqfqs4nwv330ua2g2wkjs0r77h3smwr76n
action provide_liquidity
sender terra1tpwggr4zdn2v7kat68wk398h8jk4mesqm2a3zw
receiver terra1tpwggr4zdn2v7kat68wk398h8jk4mesqm2a3zw
assets 300terra1x62dfgzrsksyemwuljhw9x0qcxefd3tpp4ued8, 3000000terra1uewxz67jhhhs2tj97pfm2egtk7zqxuhenm4y4m
share 29000
refund_assets	0terra1x62dfgzrsksyemwuljhw9x0qcxefd3tpp4ued8, 0terra1uewxz67jhhhs2tj97pfm2egtk7zqxuhenm4y4m
```

**Comment by jbamlee** [comment]
IMO, it is better to have an additional message.
- It is possible to parse but not efficient 
(must recheck all wasm messages to find `mint` to pair or user from the pair's Lp.)
- The event messages are ambiguous (need to guess whether the message "share" is intended for an individual user or a pair)

```
_contract_address terra1g6c5wrcw0sfhgl7nh2pun7v4jqfqs4nwv330ua2g2wkjs0r77h3smwr76n
action provide_liquidity
sender terra1tpwggr4zdn2v7kat68wk398h8jk4mesqm2a3zw
receiver terra1tpwggr4zdn2v7kat68wk398h8jk4mesqm2a3zw
assets 300terra1x62dfgzrsksyemwuljhw9x0qcxefd3tpp4ued8, 3000000terra1uewxz67jhhhs2tj97pfm2egtk7zqxuhenm4y4m
share 29000
refund_assets	0terra1x62dfgzrsksyemwuljhw9x0qcxefd3tpp4ued8, 0terra1uewxz67jhhhs2tj97pfm2egtk7zqxuhenm4y4m
```

I think having the current version is ok, but I wish to have an additional message later.

**Pull request merged**
